
@url = http://localhost:4600

# @url = 



GET  {{url}}/products

###

GET {{url}}/products/2



###

GET {{url}}/allProducts



###

POST {{url}}/login
//Do not forget to add two lines
Content-Type: application/json


{
    "user_name": "sachi",
    "password": "111"

}


###

POST http://localhost:4600/newProducts
Content-Type: application/json


{
   "image1": "test from server",
   "image2": "test",
    "title": "test",
    "description": "test",
    "original_price":100,
    "price" : 100,
    "stock":"available",
    "display":"online"






}

###

PUT http://localhost:4600/update
Content-Type: application/json


{  "id": "31",
   "image1": "test from server",
   "image2": "test",
    "title": "test",
    "description": "test",
    "original_price":100,
    "price" : 100,
    "stock":"available",
    "display":"online"

}


###

DELETE {{url}}/deleteproduct/62




###
GET https://cms.sachigoto.me/api/green-products/2?populate=deep


###
GET https://ecommerce.server.sachigoto.me/allproducts

###
GEThttps://cms.yukayamamoto.me/api/lost-and-founds




